---

- name: install razor
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - razor
    - pyzor

- name: configure razor and pyzor
  command: "razor-admin -create && razor-admin -register && pyzor discover"  
  become: true
  become_user: amavis



