---

- include: spamassassin.yml
  static: yes 

- include: amavis.yml
  static: yes 

- include: opendkim.yml
  static: yes

- include: postfix.yml
  static: yes 

- include: dovecot.yml
  static: yes 

